timeout: 7200s
options:
  pool:
    name: 'projects/cobalt-tools/locations/us-central1/workerPools/cobalt-windows-builder'
steps:
        - name: gcr.io/cloud-builders/gcloud
          entrypoint: "bash"
          args:
                  - "-c"
                  - |
                      curl "http://metadata.google.internal/computeMetadata/v1/project/numeric-project-id" -H "Metadata-Flavor: Google"
                      gcloud compute instances describe `hostname` | grep email:
