timeout: 7200s
options:
  machineType: N1_HIGHCPU_8
steps:
- name: 'gcr.io/cobalt-demo-330821/docker-compose'
  args: ['build',
         'build-base',
         'build-android',
         'build-evergreen',
         'stub',
         'raspi']
  env:
    - 'NINJA_STATUS="[%f/%t %c/sec] "'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
