name: Test Artifact Upload
description: Uploads test archives to GCS and runs on-device tests.
inputs:
  type:
    description: "Type of artifacts to upload (ondevice or onhost)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Configure Environment
      run: |
        set -x
        project_name=$(gcloud config get-value project)
        if [ -z ${COBALT_BOOTLOADER+x} ]
        then
          PLATFORM=${{matrix.platform}}
          echo "TARGET_PLATFORM=${{matrix.target_platform}}" >> $GITHUB_ENV
        else
          PLATFORM=${COBALT_BOOTLOADER}
          echo "TARGET_PLATFORM=${COBALT_BOOTLOADER}" >> $GITHUB_ENV
        fi
        
        if [ "${{ inputs.type }}" == 'ondevice' ]
        then
          echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/builder_tmp/${PLATFORM}_${{matrix.config}}/artifacts.tar" >> $GITHUB_ENV
        elif [ "${{ inputs.type }}" == 'onhost' ]
        then
          echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/out/tmp/${PLATFORM}_${{matrix.config}}/${PLATFORM}_${{matrix.config}}.tar.xz" >> $GITHUB_ENV
        fi

        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        project_name=$(gcloud config get-value project)
        echo "DESTINATION_PATH=${project_name}-test-artifacts/${{github.workflow}}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}_${{matrix.config}}/" >> $GITHUB_ENV
      shell: bash
    - name: Create Test Files Archive
      run: |
        set -x
        if [ "${{ inputs.type }}" == 'ondevice' ]
        then
          python3 $GITHUB_WORKSPACE/tools/create_archive.py --test_infra -d ${{env.ARCHIVE_FILE_PATH}} -s $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}}
        elif [ "${{ inputs.type }}" == 'onhost' ]
        then
          python3 $GITHUB_WORKSPACE/tools/create_archive.py --intermediate -d ${{env.ARCHIVE_FILE_PATH}} -s $GITHUB_WORKSPACE/out/${TARGET_PLATFORM}_${{matrix.config}} --parallel
        fi
      shell: bash
    - name: Copy Test Files to GCS
      id: upload-test-archive
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ${{env.ARCHIVE_FILE_PATH}}
        destination: ${{env.DESTINATION_PATH}}
