name: Upload Nightly Artifacts
description: Archives and uploads nightly artifacts to GCS bucket.
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Set env vars
      run: |
        echo "ARCHIVE_FILE_NAME=cobalt-${{matrix.platform}}_${{matrix.config}}.tar.gz" >> $GITHUB_ENV
        echo "ARCHIVE_FILE_PATH=$GITHUB_WORKSPACE/cobalt-${{matrix.platform}}_${{matrix.config}}.tar.gz" >> $GITHUB_ENV
        echo "PROJECT_NAME=$(gcloud config get-value project)" >> $GITHUB_ENV
        echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
        echo "WORKFLOW=${{github.workflow}}" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      shell: bash
    - name: Create Archive
      run: tar -czvf ${ARCHIVE_FILE_PATH} -C $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}}/install .
      shell: bash
    - name: Upload Archive
      id: upload-archive
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ${{env.ARCHIVE_FILE_PATH}}
        destination: ${{env.PROJECT_NAME}}-build-artifacts/${{env.WORKFLOW}}/${{env.TODAY}}/${{env.GITHUB_RUN_NUMBER}}/
