# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mobile_harness_gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mobile_harness_gateway.proto',
  package='mobile_harness_gateway',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cmobile_harness_gateway.proto\x12\x16mobile_harness_gateway\"5\n\x14MobileHarnessCommand\x12\x0f\n\x07workdir\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t\")\n\x15MobileHarnessResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\x89\x01\n\x16mobile_harness_gateway\x12o\n\x0c\x65xec_command\x12,.mobile_harness_gateway.MobileHarnessCommand\x1a-.mobile_harness_gateway.MobileHarnessResponse\"\x00\x30\x01\x62\x06proto3'
)




_MOBILEHARNESSCOMMAND = _descriptor.Descriptor(
  name='MobileHarnessCommand',
  full_name='mobile_harness_gateway.MobileHarnessCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workdir', full_name='mobile_harness_gateway.MobileHarnessCommand.workdir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='args', full_name='mobile_harness_gateway.MobileHarnessCommand.args', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=109,
)


_MOBILEHARNESSRESPONSE = _descriptor.Descriptor(
  name='MobileHarnessResponse',
  full_name='mobile_harness_gateway.MobileHarnessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='mobile_harness_gateway.MobileHarnessResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['MobileHarnessCommand'] = _MOBILEHARNESSCOMMAND
DESCRIPTOR.message_types_by_name['MobileHarnessResponse'] = _MOBILEHARNESSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MobileHarnessCommand = _reflection.GeneratedProtocolMessageType('MobileHarnessCommand', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEHARNESSCOMMAND,
  '__module__' : 'mobile_harness_gateway_pb2'
  # @@protoc_insertion_point(class_scope:mobile_harness_gateway.MobileHarnessCommand)
  })
_sym_db.RegisterMessage(MobileHarnessCommand)

MobileHarnessResponse = _reflection.GeneratedProtocolMessageType('MobileHarnessResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOBILEHARNESSRESPONSE,
  '__module__' : 'mobile_harness_gateway_pb2'
  # @@protoc_insertion_point(class_scope:mobile_harness_gateway.MobileHarnessResponse)
  })
_sym_db.RegisterMessage(MobileHarnessResponse)



_MOBILE_HARNESS_GATEWAY = _descriptor.ServiceDescriptor(
  name='mobile_harness_gateway',
  full_name='mobile_harness_gateway.mobile_harness_gateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=155,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='exec_command',
    full_name='mobile_harness_gateway.mobile_harness_gateway.exec_command',
    index=0,
    containing_service=None,
    input_type=_MOBILEHARNESSCOMMAND,
    output_type=_MOBILEHARNESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOBILE_HARNESS_GATEWAY)

DESCRIPTOR.services_by_name['mobile_harness_gateway'] = _MOBILE_HARNESS_GATEWAY

# @@protoc_insertion_point(module_scope)
