name: android-arm_nightly_23.lts.1+

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm
