name: android-x86.nightly

on:
  schedule:
    - cron: '* 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-x86
