name: android-arm64

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    if: github.event_name != 'label' || github.event.label.name == 'runtest'
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW
