name: Auth GITHUB_TOKEN

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        run: |
          curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/installation/repositories
      - name: Auth 2
        run: |
          curl -i -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" https://api.github.com/app/installations
      - name: Auth 3
        run: |
          curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/app/installations
