# Reusable Cobalt build workflow.

name: Build

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image name.'
        required: true
        type: string

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    name: ${{matrix.platform}}-${{matrix.config}}
    container: ghcr.io/isarkis/${{inputs.image}}:main
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set Android env vars
        if: startsWith(${{matrix.target_platform}}, 'android')
        run: |
          echo "ANDROID_HOME=/root/starboard-toolchains/AndroidSdk/" >> $GITHUB_ENV
          echo "GCS_NIGHTLY_PATH=gs://cobalt-actions-devel-build-artifacts" >> $GITHUB_ENV
      - name: Build ${{matrix.platform}}-${{matrix.config}}
        uses: ./.github/actions/build
