# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  packages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-image-build:
    strategy:
      fail-fast: false
      matrix:
        service:
          - build-android
          - build-base
          - build-evergreen
          - build-linux
          - build-linux-stub
          - build-raspi

    runs-on: ubuntu-latest
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v2

      - name: Retrieve Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cobalt-${{ matrix.service }} 

      - name: Build containers with docker-compose
        uses: smartlyio/docker-compose-action@v1
        with:
          serviceName: ${{ matrix.service }}
          build: false
          push: "on:push"
          composeArguments: "--no-start"

      - name: Tag images
        run: docker tag cobalt-${{ matrix.service }} ${{ steps.meta.outputs.tags }}

      - name: Push images
        if: github.event_name != 'pull_request'
        run: docker push ${{ steps.meta.outputs.tags }}

  # Raspi Jobs.
  raspi:
    needs: docker-image-build
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]
    name: ${{matrix.platform}}-${{matrix.config}}
    # Create config matrix
    strategy:
      fail-fast: false
      matrix:
        platform: [raspi-2,
                   raspi-2-skia,
                   raspi-2-skia-sbversion-12,
                   raspi-2-skia-sbversion-13,
                   raspi-2-sbversion-12,
                   raspi-2-sbversion-13,
                   raspi-2-evergreen-arm-hardfp,
                   raspi-2-evergreen-arm-hardfp-sbversion-12,
                   raspi-2-evergreen-arm-hardfp-sbversion-13]
        config: [devel, debug]
      # The container to run the job in.
    container: ghcr.io/isarkis/cobalt-build-raspi:main
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Run build
      - name: ${{matrix.platform}}-${{matrix.config}}
        run: |
          $GITHUB_WORKSPACE/cobalt/build/gyp_cobalt -v -C ${{ matrix.config }} ${{ matrix.platform }}
          ninja -v -j 8 -C $GITHUB_WORKSPACE/out/${{ matrix.platform }}_${{ matrix.config }} eztime_test_deploy nplb_deploy app_launcher_zip
  
  # Evergreen jobs.
  evergreen:
    needs: docker-image-build
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]
    name: ${{matrix.platform}}-${{matrix.config}}
    # Create config matrix
    strategy:
      fail-fast: false
      matrix:
        platform: [evergreen-x86,
                   evergreen-x86-sbversion-13,
                   evergreen-x86-sbversion-12,
                   evergreen-arm-softfp,
                   evergreen-arm-softfp-sbversion-13,
                   evergreen-arm-softfp-sbversion-12,
                   evergreen-arm64,
                   evergreen-arm64-sbversion-13,
                   evergreen-arm64-sbversion-12]
        config: [devel, debug]
    container: ghcr.io/isarkis/cobalt-build-evergreen:main
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Run build
      - name: ${{matrix.platform}}-${{matrix.config}}
        run: |
          $GITHUB_WORKSPACE/cobalt/build/gyp_cobalt -v -C ${{ matrix.config }} ${{ matrix.platform }}
          ninja -v -j 8 -C $GITHUB_WORKSPACE/out/${{ matrix.platform }}_${{ matrix.config }} eztime_test_deploy nplb_deploy app_launcher_zip
  
  # XB1 Jobs.
  xb1:
    needs: docker-image-build
    # The type of runner that the job will run on
    runs-on: [self-hosted, X64, windows]
    name: ${{matrix.platform}}-${{matrix.config}}
    # Create config matrix
    strategy:
      fail-fast: false
      matrix:
        platform: [xb1]
        config: [devel, debug]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout cobalt repo.
      # - uses: actions/checkout@v2
      # Run build
      - name: echo
        run: |
          powershell echo ${{matrix.platform}}-${{matrix.config}}
