# Reusable Cobalt docker image build workflow.

name: Docker

on:
  workflow_call:
    inputs:
      service:
        description: 'Type of workflow to run.'
        required: true
        type: string

# Global env vars.
env:
  REGISTRY: ghcr.io

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-image-build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 
      - name: Get docker file changes
        id: changed-files
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            docker-compose.yml
            docker/**
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') && (github.event_name != 'pull_request') }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve Docker metadata
        if: steps.changed-files.outputs.any_changed == 'true'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cobalt-${{ inputs.service }} 
      - name: Build containers with docker-compose
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: smartlyio/docker-compose-action@v1
        with:
          serviceName: ${{ inputs.service }}
          build: false
          push: "on:push"
          composeArguments: "--no-start"
      - name: Tag images
        if: steps.changed-files.outputs.any_changed == 'true'
        run: docker tag cobalt-${{ inputs.service }} ${{ steps.meta.outputs.tags }}
      - name: Push images
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') && (github.event_name != 'pull_request') }}
        run: docker push ${{ steps.meta.outputs.tags }}
