# This is a basic workflow to help you get started with Actions

name: evergreen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  evergreen:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, X64]
    name: ${{matrix.platform}}-${{matrix.config}}
    # Create config matrix
    strategy:
      matrix:
        platform: [evergreen-x86,
                   evergreen-x86-sbversion-13,
                   evergreen-x86-sbversion-12,
                   evergreen-arm-softfp,
                   evergreen-arm-softfp-sbversion-13,
                   evergreen-arm-softfp-sbversion-12,
                   evergreen-arm64,
                   evergreen-arm64-softfp-sbversion-13,
                   evergreen-arm64-softfp-sbversion-12]
        config: [devel, debug]
      # The container to run the job in.
    container: ghcr.io/kaidokert/cobalt-build-evergreen:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Run build
      - name: ${{matrix.platform}}-${{matrix.config}}
        run: |
          $GITHUB_WORKSPACE/cobalt/build/gyp_cobalt -v -C ${{ matrix.config }} ${{ matrix.platform }}
          ninja -v -j 8 -C $GITHUB_WORKSPACE/out/${{ matrix.platform }}_${{ matrix.config }} eztime_test_deploy nplb_deploy app_launcher_zip
