name: evergreen_x86

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      service: build-evergreen
  build:
    needs: docker
    strategy:
      fail-fast: false
      matrix:
        platform: [evergreen-x86,
                   evergreen-x86-sbversion-14,
                   evergreen-x86-sbversion-13,
                   evergreen-x86-sbversion-12]
        config: [devel, debug, gold, qa]
        include:
          - platform: evergreen-x86
            target_platform: evergreen-x86
            target_cpu: target_cpu=\"x86\"
            use_asan: use_asan=false
          - platform: evergreen-x86-sbversion-14
            target_platform: evergreen-x86
            target_cpu: target_cpu=\"x86\"
            use_asan: use_asan=false
            sb_api_version: sb_api_version=14
          - platform: evergreen-x86-sbversion-13
            target_platform: evergreen-x86
            target_cpu: target_cpu=\"x86\"
            use_asan: use_asan=false
            sb_api_version: sb_api_version=13
          - platform: evergreen-x86-sbversion-12
            target_platform: evergreen-x86
            target_cpu: target_cpu=\"x86\"
            use_asan: use_asan=false
            sb_api_version: sb_api_version=12
    container: ghcr.io/isarkis/cobalt-build-evergreen:main
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build ${{matrix.platform}}-${{matrix.config}}
        uses: ./.github/actions/build
