name: evergreen-arm-softfp

on:
  pull_request:
    types: [ready_for_review]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW

