name: linux_nightly

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux
