name: linux-gcc-6-3

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW

