# Reusable Cobalt CI workflow.

name: CI

on:
  workflow_call:
    inputs:
      platform:
        description: 'Cobalt platform.'
        required: true
        type: string

# Global env vars.
env:
  REGISTRY: ghcr.io
  IPV6_AVAILABLE: 0
  IS_BUILDBOT_DOCKER: 1
  #BUILD_ID_SERVER_URL:
  IS_CI: 1
  IS_DOCKER: 1
  NINJA_STATUS: '[%e sec | %f/%t %u remaining | %c/sec | j%r]'
  SCCACHE: 1
  SCCACHE_GCS_BUCKET: cobalt-actions-devel-sccache-linux
  SCCACHE_GCS_OAUTH_URL: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
  SCCACHE_GCS_RW_MODE: READ_WRITE

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Builds, tags, and pushes Cobalt docker images to ghr.
  docker-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 
      
      - name: Get docker file changes
        id: changed-files
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            docker-compose.yml
            docker/**

      - id: get-docker-service
        run: |
          export docker_service=$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -r '.docker_service')
          echo "::set-output name=docker_service::$docker_service"
          echo "docker_service=$docker_service" >> $GITHUB_ENV
          echo $docker_service

      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') && (github.event_name != 'pull_request') }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve Docker metadata
        if: steps.changed-files.outputs.any_changed == 'true'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cobalt-${{ env.docker_service }}

      - name: Build containers with docker-compose
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: smartlyio/docker-compose-action@v1
        with:
          serviceName: ${{ env.docker_service }}
          build: false
          push: "on:push"
          composeArguments: "--no-start"

      - name: Tag images
        if: steps.changed-files.outputs.any_changed == 'true'
        run: docker tag cobalt-${{ env.docker_service }} ${{ steps.meta.outputs.tags }}

      - name: Push images
        if: ${{ (steps.changed-files.outputs.any_changed == 'true') && (github.event_name != 'pull_request') }}
        run: docker push ${{ steps.meta.outputs.tags }}
    outputs:
      docker_service: ${{ steps.get-docker-service.outputs.docker_service }}

  # Generates build matrix based on json configuration file.
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: set-platforms
        run: echo "::set-output name=platforms::$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -c '.platforms')"
      - id: set-includes
        run: echo "::set-output name=includes::$(cat ${GITHUB_WORKSPACE}/.github/config/${{ inputs.platform }}.json | jq -c '.includes')"
    outputs:
      platforms: ${{ steps.set-platforms.outputs.platforms }}
      includes: ${{ steps.set-includes.outputs.includes }}
  # Runs Cobalt CI workflow.
  build:
    needs: [docker-image, build-matrix]
    runs-on: [self-hosted, linux, X64]
    name: ${{matrix.platform}}_${{matrix.config}}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(needs.build-matrix.outputs.platforms) }}
        include: ${{ fromJson(needs.build-matrix.outputs.includes) }}
        config: [devel, debug, qa, gold]
    container: ghcr.io/${{ github.repository_owner }}/cobalt-${{ needs.docker-image.outputs.docker_service }}:main
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set env vars
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "STARBOARD_TOOLCHAINS_DIR=/root/starboard-toolchains" >> $GITHUB_ENV
      - name: Set Android env vars
        if: startsWith(${{matrix.target_platform}}, 'android')
        run: |
          echo "ANDROID_HOME=/root/starboard-toolchains/AndroidSdk/" >> $GITHUB_ENV
          echo "GCS_NIGHTLY_PATH=gs://cobalt-actions-devel-build-artifacts" >> $GITHUB_ENV
      - name: Print env vars
        run: env | sort
      - name: "gn gen"
        run: |
          gn gen $GITHUB_WORKSPACE/out/${{matrix.target_platform}}_${{matrix.config}} --args="target_platform=\"${{matrix.target_platform}}\" ${{matrix.use_asan}} ${{matrix.is_clang}} ${{matrix.using_old_compiler}} ${{matrix.sb_api_version}} ${{matrix.target_os}} ${{matrix.target_cpu}} is_internal_build=false build_type=\"${{matrix.config}}\""
      - name: "gn check"
        run: |  
          gn check $GITHUB_WORKSPACE/out/${{ matrix.target_platform }}_${{ matrix.config }}
      - name: Build ${{matrix.platform}}-${{matrix.config}}
        shell: bash
        run: |
          set -x
          ln -s /root/starboard-toolchains /github/home/starboard-toolchains
          target=all
          if [[ "${{ matrix.config }}" =~ ^(qa|gold)$ ]]; then
            target=default
          fi
          ninja -v -C ${GITHUB_WORKSPACE}/out/${{ matrix.target_platform }}_${{ matrix.config }} ${target}
  
  #win-win32:
  #  needs: docker-image-build
    # The type of runner that the job will run on
    #  runs-on: [self-hosted, X64, windows]
    #name: ${{matrix.platform}}-${{matrix.config}}
    # Create config matrix
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    platform: [win-win32]
    #    config: [devel, debug]
    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
      # Checkout cobalt repo.
      # - uses: actions/checkout@v2
      # Run build
      # - name: echo
      #  run: |
      #    powershell echo ${{matrix.platform}}-${{matrix.config}}
