name: raspi-2.nightly

on:
  schedule:
    - cron: '* 14 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: raspi-2
