name: test_labeled
on:
  pull_request:
    types:
      - labeled
jobs:
  test1:
    if: github.event.label.name == 'runtest'
    runs-on: [ubuntu-latest]
    steps:
      - name: say hello
        run: |
          echo say hello
      - name: test
        run: |
          echo test
