name: Test
on:
  issue_comment:                                     
    types: [created]

jobs:
 test1:
   if: contains(github.event.comment.body, '/test')
   runs-on: [ubuntu-latest]
   steps:
     - name: say hello
       run: |
         echo say hello
     - name: test
       run: |
         echo test
