name: win32

on:
  pull_request:
    types: [ready_for_review]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    if: github.event_name != 'label' || github.event.label.name == 'runtest'
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: $GITHUB_WORKFLOW
